apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubernetes-demo
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-demo
        version: "1.0"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kubernetes-demo
          image: krisawatson/k8s-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8237
          livenessProbe:
            httpGet:
              path: /health
              port: 8237
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: demo-secret
              mountPath: "/etc/demo-secret"
              readOnly: true
      volumes:
        - name: demo-secret
          secret:
            secretName: my-demo-secret
