apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo
  namespace: demo
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: kubernetes-demo
    image: krisawatson/k8s-demo:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8237
    livenessProbe:
      httpGet:
        path: /health
        port: 8237
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 10