apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-1
  namespace: demo
spec:
  selector:
    app: kubernetes-demo
    version: "1.0"
  ports:
    - protocol: TCP
      port: 8237
      targetPort: 8237
      nodePort: 30237
  type: NodePort