---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: kubernetes-demo
  namespace: demo
spec:
  serviceName: kubernetes-demo-1
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
        version: "1.0"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kubernetes-demo
        image: krisawatson/k8s-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8237
        livenessProbe:
          httpGet:
            path: /health
            port: 8237
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - mountPath: /tmp/data
          name: pvc-volume
  volumeClaimTemplates:
    - metadata:
        name: pvc-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
